---
title: Awesome Digital History
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel
date-modified: 2024-03-14
categories: Other
lang: de
citation:
  type: standard
code-links:
  - href: 'https://github.com/maehr/awesome-digital-history/'
    text: GitHub Repository
    icon: github
other-links:
  - text: Website
    icon: collection
    href: 'https://awesome-digital-history.pages.dev/'
---

Das [Awesome Digital History](https://github.com/maehr/awesome-digital-history/) Projekt ist eine sorgfältig zusammengestellte Sammlung von Online-Ressourcen, die Forschende und Interessierte dabei unterstützt, digitale Geschichtsforschung zu betreiben. Der Fokus liegt auf der Bereitstellung von Hilfsmitteln zum Auffinden von textuellen und multimedialen Primärquellen, insbesondere aus dem westlichen Kulturkreis und den Epochen des 19. und 20. Jahrhunderts. Zusätzlich bietet die Sammlung Zugang zu Kursen und Lernmaterialien, die den Einstieg in die digitale Geschichtsforschung erleichtern. Die dazugehörige Webseite [awesome-digital-history.pages.dev](https://awesome-digital-history.pages.dev/) erweitert diese Sammlung durch eine benutzerfreundliche Oberfläche. Nutzer*innen können die verfügbaren Ressourcen nach verschiedenen Kriterien filtern, wie beispielsweise Region, Sprache, Medientyp oder historische Periode. Dies ermöglicht eine gezielte und effiziente Recherche nach spezifischen historischen Materialien. Das Team von **Stadt.Geschichte.Basel** hat aktiv an der Entwicklung dieses Projekts mitgewirkt. Das Projekt ist offen gestaltet und lädt die Community ein, durch Beiträge und Vorschläge die Sammlung kontinuierlich zu erweitern und zu verbessern. 