---
title: Code Management Workflow
subtitle: Kollaboratives Arbeiten mit GitHub
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel
  - name: Nico Görlich
    orcid: 0000-0003-3860-1488
    affiliation: Universität Basel
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
category: Interna
date-modified: last-modified
lang: de
code-links:
  - href: 'https://github.com/Stadt-Geschichte-Basel'
    text: GitHub-Organisation
    icon: github
---

## Kollaboratives Arbeiten

Das [GitHub-Repository von Stadt.Geschichte.Basel](https://github.com/Stadt-Geschichte-Basel/) dient als zentrale Plattform für die Entwicklung und Verwaltung der digitalen Projekte rund um die Basler Stadtgeschichte. Hier werden verschiedene Repositories gepflegt, darunter:

-   [stadtgeschichtebasel.ch](https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch): Der Open-Source-Code des digitalen Portals von Stadt.Geschichte.Basel, entwickelt mit SvelteKit und gehostet auf Cloudflare Pages.

-   [forschung.stadtgeschichtebasel.ch](https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch): Der Quellcode der Forschungsdatenplattform, basierend auf CollectionBuilder-CSV und gehostet auf GitHub Pages.

Für die Zusammenarbeit setzt das Team auf einen Fork-and-Pull-Workflow. Externe Beitragende können das Repository forken, Änderungen vornehmen und anschliessend Pull Requests einreichen. Dieses Vorgehen ermöglicht eine kontrollierte Integration von Beiträgen und fördert eine offene Entwicklungskultur.

Zusätzlich nutzt das Projekt GitHub Issues zur Verwaltung von Aufgaben und zur Nachverfolgung von Fehlern. Dies erleichtert die Kommunikation innerhalb des Teams und mit der Community, indem es eine transparente und strukturierte Plattform für Diskussionen und Problemlösungen bietet.

Durch diese Arbeitsweise wird sichergestellt, dass die Entwicklung der digitalen Angebote von Stadt.Geschichte.Basel effizient, kollaborativ und nachvollziehbar verläuft.