---
title: "Forschungsdatenmanagement & Public History der Stadt.Geschichte.Basel"
subtitle: "Willkommen auf der Dokumentationsplattform von Stadt.Geschichte.Basel"
description: "Startseite der Dokumentationsplattform des Teams Forschungsdatenmanagement (RDM) und Public History von Stadt.Geschichte.Basel. Wir dokumentieren unsere Arbeit mit Forschungsdaten, digitaler Präsentation und Vermittlung."
keywords:
  - Stadt.Geschichte.Basel
  - RDM
  - Forschungsdatenmanagement
  - Public History
  - Digital History
  - Basel
  - Stadtgeschichte
  - Dokumentation
  - Metadaten
  - Data Stories
  - Digitale Vermittlung
lang: de
listing:
  - id: showcase-reel
    type: grid
    contents:
      - products/*/*/index.qmd
    sort-ui: false
    filter-ui: false
    fields: [title, subtitle, date, categories]
    page-size: 1000
date-modified: last-modified
include-in-header: assets/js/random-listing-js.html
---

Diese Webseite zeigt die Arbeit des Teams für Forschungsdatenmanagement und Public History von Stadt.Geschichte.Basel. Im Fokus steht neben unserer Arbeit mit Forschungsdaten (Erstellung, Annotation, Publikation, Weiterverwendung) die Aufbereitung der Projektinhalte für die digitale Präsentation und Vermittlung. Wir dokumentieren auch projektbezogene Vorträge, Poster und Workshops im Rahmen von wissenschaftlichen Konferenzen sowie unsere Beteiligung an Community Building im Bereich Digital History.

## Produkte

Von unserem Team erarbeitete Lösungen bieten wir als Good-Practice-Beispiele zur Weiterverwendung an, darunter ein Handbuch zur Erstellung diskriminierungsfreier Metadaten für historische Quellen und Forschungsdaten, Workflows für kollaboratives Projektmanagement und [weitere Produkte](/products/products.qmd), zum Beispiel:

::: {#showcase-reel}
:::

## Stadt.Geschichte.Basel

Wir sind ein interdisziplinäres [Forschungsprojekt](about.qmd), das sich der umfassenden Erforschung und Dokumentation der langen Geschichte von Basel widmet. Über 70 Forscher\*innen und Mitarbeiter\*innen aus verschiedenen Ländern untersuchen die Geschichte Basels von den ersten Siedlungsspuren bis heute. Unser Ziel ist es, einen bedeutenden Beitrag zur Erforschung und Dokumentation der Geschichte von Basel zu leisten und gleichzeitig die Vergangenheit auf zeitgemässe Weise zugänglich zu machen.