---
title: Diskriminierungsfrei? Erfahrungen aus einem Handbuchprojekt
author:
  - name: Noëlle Schnegg
    orcid: 0009-0008-5207-6652
    email: noelle.schnegg@unibas.ch
    affiliation: Universität Basel
  - name: Levyn Bürki
    orcid: 0009-0009-7602-0714
    affiliation: Universität Bern
date: 2024-11-21
categories: Vortrag
event: Herder-Institut Marburg, Große Anforderungen an kleine Textfelder
lang: de
# doi: FIXME
bibliography: references.bib
nocite: |
  @*
citation:
  type: standard
  title: 'Diskriminierungsfrei? Erfahrungen aus einem Handbuchprojekt'
  container-title: 'Grosse Anforderungen an kleine Textfelder: Ethische Fragen an Metadaten historischer Quellen, Herder-Institut für historische Ostmitteleuropaforschung, Marburg'
appendix-cite-as: display
other-links:
  - text: Veranstaltungsankündigung
    icon: house
    href: 'https://www.hsozkult.de/event/id/event-150327'
  - text: Veranstaltungsbericht
    icon: journal-richtext
    href: 'https://www.herder-institut.de/blog/2024/12/12/grosse-anforderungen-an-kleine-textfelder/'
#  - text: 'Slides (Zenodo)'
#    icon: filetype-pdf
#    href:
---

## Vortrag

Der Vortrag "Diskriminierungsfrei? Erfahrungen aus einem Handbuchprojekt" ist Teil des Workshops "Grosse Anforderungen an kleine Textfelder: Ethische Fragen an Metadaten historischer Quellen" (21.-22.11.2024) am Herder-Institut in Marburg.

<!--
::: {.callout-tip title="Präsentation anzeigen" icon="false" collapse="true"}
<iframe src="FIXME" width="100%" height="600px" loading="lazy" allowfullscreen title="Diskriminierungsfrei? Erfahrungen aus einem Handbuchprojekt">

This browser does not support PDFs. Please download the PDF <a href="FIXME">download the PDF</a> to view it.

</iframe>
:::
-->

## Abstract

Noëlle Schnegg (Universität Basel) und Levyn Bürki (Universität Bern) teilen ihre Erfahrung aus der Arbeit an einem [Handbuch zum diskriminierungssensiblen Umgang mit Metadaten im Kontext historischer Quellen und Forschungsdaten](/products/publications/handbuch/index.qmd). Das Handbuch wurde im Juni im Rahmen des Forschungsprojekts Stadt.Geschichte.Basel von Moritz Mähr und Noëlle Schnegg als *Living Document* veröffentlicht und wird derzeit (Stand 11/2024) überarbeitet.

Im Kontext aktueller Initiativen und weiterer Leitfäden stellen Schnegg und Bürki das Handbuch kurz vor und diskutieren dabei wichtige Nuancen hinsichtlich Terminologie, Fokussetzung und Autor:innenschaft. Dabei werfen sie einen kritischen Blick auf Begriffe wie "diskriminierungsfrei", "dekolonial" und "Bias" und erörtern, weshalb es bei der Auseinandersetzung mit den kleinen Textfeldern um weit mehr als bloss um Vokabeln geht.

Anhand konkreter Beispiele gehen sie auf Herausforderungen im Umgang mit Metadaten ein, die auch zu wertvollem Feedback geführt haben. Thematisieren werden sie etwa die Autor:innenschaft von Metadaten, die Relevanz einer Metadtaten-Versionierung, den Einsatz von Beispielen sowie das Risiko von Diskriminierung bei Übersetzungen oder beim Mapping zwischen Ontologien. Abschliessend diskutieren sie über Zielgruppen solcher Handbücher und Leitfäden und erwägen mögliche Synergien bei deren Erarbeitung.