---
title: Barrierefreiheitserklärung
category: Interna
author: 
- name: Cristina Münch
  affiliation: Universität Basel
  orcid: 0000-0003-3885-248X
- name: Nico Görlich
  affiliation: Universität Basel
  orcid: 0000-0003-3860-1488
- name: Moritz Mähr
  email: moritz.maehr@gmail.com
  affiliation: Universität Basel
  orcid: 0000-0002-1367-1618
- name: Moritz Twente
  affiliation: Universität Basel
  orcid: 0009-0005-7187-9774
  email: mtwente@protonmail.com
date: March 2024
date-format: "MMMM YYYY"
lang: de-CH
---

Wir bemühen uns, die Online-Angebote von Stadt.Geschichte.Basel gemäss den aktuellen Webstandards und den Anforderungen der Barrierefreiheit zu [gestalten](../inklusive-gestaltung/index.qmd). Unsere Barrierefreiheitserklärung beschreibt, welche Massnahmen wir umsetzen, um die Zugänglichkeit zu gewährleisten. Für die Online-Angebote der Stadt.Geschichte.Basel gilt die folgende Barrierefreiheitserklärung, wie sie auf unserem [Portal](https://stadtgeschichtebasel.ch/barrierefreiheitserklaerung) verfügbar ist.

## Einleitung

Das Team der Stadt.Geschichte.Basel  ist der Überzeugung, dass der Zugang zu Informationen und Kommunikation ein grundlegendes Menschenrecht ist. Stadt.Geschichte.Basel verpflichtet sich daher, ein barrierefreies Webangebot zu gestalten: Alle Inhalte und Dienstleistungen des Webangebots von Stadt.Geschichte.Basel sollen möglichst einfach und uneingeschränkt für Besucher\*innen mit unterschiedlichen Fähigkeiten oder Einschränkungen zugänglich sein.

In diesem Sinne dient die folgende Barrierefreiheitserklärung als Selbstverpflichtung des Teams, die Website barrierefrei zu halten und sich laufend in diesem Bereich zu verbessern. Die Bemühungen zur Sicherstellung der Barrierefreiheit umfassen die Einhaltung international anerkannter Standards und Best Practices, die Schulung der Mitarbeiter\*innen in barrierefreiem Webdesign sowie die ständige Überprüfung und Verbesserung des Portals, um sicherzustellen, dass sie den Bedürfnissen aller Nutzer\*innen gerecht wird. 

Die Erklärung ist ausserdem eine Dokumentation der Schritte, die bereits im Bereich Barrierefreiheit umgesetzt wurden. Seit Beginn des Projektes wurde darauf geachtet, Webseite und Inhalte mit der Barrierefreiheitserklärung abzugleichen. Stadt.Geschichte.Basel ist bestrebt, das Portal kontinuierlich auf die Einhaltung der neuesten Standards zu prüfen und deren Umsetzung zu verbessern. Die Ergebnisse der Prüfungen werden im Abschnitt [Aktueller Status](#aktueller-status) festgehalten. Das Team ist stets offen für Rückmeldungen und Anregungen.

## Geltungsbereich
Diese Barrierefreiheitserklärung gilt als Selbstverpflichtung grundsätzlich für alle von Stadt.Geschichte.Basel konzipierten Websites, das heisst für das Portal [stadtgeschichtebasel.ch](https://stadtgeschichtebasel.ch) (im Folgenden: “Portal”) und für die Forschungsdatenplattform [forschung.stadtgeschichtebasel.ch](https://forschung.stadtgeschichtebasel.ch) (im Folgenden “Forschungsdatenplattform”).

## Standards und Richtlinien
Stadt.Geschichte.Basel arbeitet aktiv daran, die international anerkannten Richtlinien für barrierefreie Webinhalte (Web Content Accessibility Guidelines, WCAG 2.1) umzusetzen und die relevanten Erfolgskriterien zu erfüllen[^1]. Die von der Web Accessibility Initiative des World Wide Web Consortiums (W3C) erarbeiteten WCAG-Richtlinien umfassen als Grundlagen für uneingeschränkten Zugang und Nutzung einer Website die vier Grundprinzipien Wahrnehmbar, Bedienbar, Verständlich und Robust.

[^1]: Die WCAG-Evaluation von [Portal](../../coding/portal/index.qmd#barrierefreiheit) und [Forschungsdatenplattform](../../coding/plattform/index.qmd#barrierefreiheit) sind auch auf dieser Webseite verfügbar.

### Wahrnehmbar (perceivable)
Dieses Grundprinzip garantiert den Umstand, dass Informationen und Komponenten der Benutzeroberfläche so dargestellt werden, dass sie wahrnehmbar sind. Beispielsweise reichen Bildbeschreibungen eines Bildes nicht aus, um vollständig sichtbar für alle Nutzer\*innen zu sein. Es ist daher zentral, jeweils neben den Bildunterschriften auch passende Alternativtexte zu schreiben, um für den Screenreader erkennbar zu sein. 

### Bedienbar (operable)
Die Komponenten der Benutzeroberfläche und die Navigation müssen bedienbar sein. Das bedeutet konkret, dass die gesamte Funktionalität des Inhalts über eine Tastatur bedienbar ist. Bestenfalls wird ausserdem darauf geachtet, dass die Verwendung anderer Hilfsmittel möglich ist. Ausserdem soll die Website so konzipiert sein, dass die Navigation und das Auffinden von Inhalten möglichst einfach für alle Nutzer\*innen ist. 

### Verständlich (understandable)
Informationen und die Bedienung der Benutzeroberfläche müssen verständlich sein. So müssen einerseits die Textinhalte lesbar und verständlich sein. Andererseits muss die Navigation innerhalb der Website nachvollziehbar für alle sein. Zuletzt sollen Eingabehilfen den Nutzer\*innen dabei helfen, unter anderem mit Identifikationsmechanismen Fehler zu vermeiden und zu korrigieren. 

### Robust
Der Inhalt muss so robust sein, dass er von einer Vielzahl von user agents, einschliesslich assistierender Technologien, zuverlässig interpretiert werden kann. Dies bedeutet, dass Benutzer\*innen in der Lage sein müssen, auf den Inhalt zuzugreifen, auch wenn sich die Technologien weiterentwickeln.

## Aktueller Status
### Schulung der Mitarbeitenden
Stadt.Geschichte.Basel bemüht sich, dass sich die Mitarbeiter*innen fortlaufend im Bereich Barrierefreiheit weiterbilden und externe Schulungen absolvieren. So wurde beispielsweise ein Kurs von der ETH Zürich besucht, welcher den Umgang mit Alternativtexten vermittelte. Die Frage “Wie schreibt man gute Alternativtexte?” stand dabei im Zentrum. Anhand von Beispielen unterschiedlicher Bildtypen wurden die Unterschiede zwischen den Alternativtexten analysiert und besprochen. Die Erkenntnisse der Schulung flossen aktiv in die Bildbearbeitungen der Website hinein. 

### Nicht barrierefreie Funktionen
Die nachstehend aufgeführten Inhalte sind aus den angegebenen Gründen nicht vollständig barrierefrei:

### Unvereinbarkeit mit den Barrierefreiheitsbestimmungen
Auf der Seite [Partner](https://stadtgeschichtebasel.ch/partner) ist eine Karte eingebunden, die nicht barrierefrei ist: diese ist Drittanbieter-Inhalt und nicht kontrollierbar. Sie bietet weitgehend redundante Informationen zu den Adress-Angaben, die als Alternativtext vorhanden sind.

### Erstellung der Erklärung zur Barrierefreiheit
Die Erklärung wurde am 5. März 2024 auf Grundlage der Barrierefreiheitserklärungen der [Stiftung Zugang für Alle](https://access-for-all.ch/barrierefreiheitserklaerung/) und der [ETH Zürich](https://ethz.ch/de/footer/barrierefreiheitserkl%C3%A4rung.html) verfasst.

## Feedback und Kontaktinformationen
Für Feedback und etwaige Mängel in Bezug auf die Einhaltung der Anforderungen an Barrierefreiheit können Sie sich per Mail an uns wenden: [info\@stadtgeschichtebasel.ch](mailto:info@stadtgeschichtebasel.ch)