---
title: Datenmodell
lang: de
format:
  sgb-theme-html:
    mermaid:
      theme: neutral
author: 
- name: Nico Görlich
  affiliation: Universität Basel
  orcid: 0000-0003-3860-1488
- name: Cristina Münch
  affiliation: Universität Basel
  orcid: 0000-0003-3885-248X
- name: Moritz Mähr
  email: moritz.maehr@gmail.com
  affiliation: Universität Basel
  orcid: 0000-0002-1367-1618
- name: Noëlle Schnegg
  affiliation: Universität Basel
  orcid: 0009-0008-5207-6652
- name: Moritz Twente
  email: mtwente@protonmail.com
  affiliation: Universität Basel
  orcid: 0009-0005-7187-9774
date-modified: last-modified
---

Metadaten für die auf der [Forschungsdatenplattform](/products/coding/plattform/index.qmd) vorgestellten Elemente werden gemäss einem Datenmodell bereitgestellt, das vom Team für Forschungdatenmanagement der Stadt.Geschichte.Basel entwickelt wurde, um den Anforderungen der vielfältigen im Projekt verwendeten Quellen gerecht zu werden. Das Datenmodell (und der anschliessende Annotationsprozess) folgen dem [Handbuch für Diskriminierungssensible Metadatenpraxis](/products/publications/handbuch/index.qmd), das ebenfalls von Stadt.Geschichte.Basel entwickelt wurde.

## Metadatenfelder

Die folgende Grafik visualisiert das Datenmodell mit Metadatenfeldern für ein Beispiel-Metadatenobjekt `abb01313`, das ein untergeordnetes Medienobjekt `m01313` hat. Wenn ein Metadatenobjekt mehr als ein untergeordnetes Medienobjekt hat, werden die id-Nummern der untergeordneten Objekte fortlaufend nummeriert: `m01313_1`, `m01313_2` usw.

```{mermaid fig-datamodel}
%%| label: fig-datamodel
%%| fig-cap: Datenmodell für die Forschungsdaten von Stadt.Geschichte.Basel.

classDiagram
    direction LR

    class metadata["metadata object"]
    class media["media object"]

    metadata "n" --> "m" media

    class media {
        id &lpar;m01313&rpar;
        title
        [subject;subject]
        description
        [abstract] &lpar;alt attribute for alternative text&rpar;
        [creator] &lpar;incl. link to Wikidata&rpar;
        [publisher] &lpar;incl. link to Wikidata&rpar;
        date &lpar;EDTF&rpar;
        temporal
        type
        format
        extent
        [source] &lpar;Source and catalogue link&rpar;
        language &lpar;ISO 639-1 code&rpar;
        [relation] &lpar;internal links, further information&rpar;
        rights
        license
    }

    class metadata {
        id &lpar;abb01313&rpar;
        title
        [subject;subject]
        description
        temporal
        language &lpar;ISO 639-1 code&rpar;
        [isPartOf;isPartOf] &lpar;Data DOIs&rpar;
    }

style metadata stroke:#777,color:#3A1E3E
style media fill:#FFFFFF,stroke:#777,color:#3A1E3E
```

Ein modifiziertes Datenmodell gilt für die Datensätze, aus denen [Diagramme und Statistiken](/products/research-data/plots/index.qmd) erstellt wurden. In diesem Zusammenhang wurden tabellarische Daten inklusive Metadaten zusätzlich auf GitHub veröffentlicht. Für diese Datensätze wurde das Datenmodell von Stadt.Geschichte.Basel [geringfügig angepasst](/products/research-data/plots/index.qmd#datenmodell), um auf die abweichenden Anforderungen an die Veröffentlichung tabellarischer Daten im Internet gemäss [W3C-Standard](https://w3c.github.io/csvw/syntax/) eingehen zu können.

### Temporal

Das Metadatenfeld `temporal` ordnet das Medien- und Metadatenobjekte einer Epoche zu. Ausgangspunkt für diese Klassifizierung ist, zu welchem Buch in der Reihe Stadt.Geschichte.Basel gehört. Zulässige Werte sind: Frühgeschichte, Antike, Mittelalter, Frühe Neuzeit, 19. Jahrhundert, 20. Jahrhundert, 21. Jahrhundert. Das `temporal`-Feld wird auf Omeka verwendet, während [CollectionBuilder bzw. die Forschungsdatenplattform](/products/coding/plattform/index.qmd) dieses Metadatenfeld mit `coverage` bezeichnen.

### Date

Stadt.Geschichte.Basel verwendet das [Extended Date Time Format (EDTF)](https://www.loc.gov/standards/datetime/), um Datums-/Zeitangaben in den Metadaten zu den veröffentlichten Daten auf der [Forschungsdatenplattform](/products/coding/plattform/index.qmd) zu erfassen.

EDTF ist ein auf [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) aufbauender Standard, der über einfache Datumsangaben hinausgeht und es ermöglicht, komplexe, unsichere, ungefähre oder mehrdeutige Zeitangaben strukturiert und maschinenlesbar festzuhalten. Die wichtigsten Funktionalitäten und Merkmale sind:

1.  **Einfache Datumsangaben**\
    Wie bei ISO 8601 üblich, kann man präzise Daten im Format `YYYY-MM-DD` angeben, z. B. `2024-12-11` für den 11. Dezember 2024.\
    Ebenfalls möglich sind Teilangaben wie `2024-12` (Dezember 2024) oder nur das Jahr `2024`.

2.  **Ungewisse und ungefähre Daten**\
    Mit speziellen Zeichen lässt sich angeben, wenn ein Datum nur ungefähr oder unsicher ist:

    -   `?` kennzeichnet Unsicherheit (z. B. `1960?` könnte bedeuten, dass es etwa 1960 war, aber nicht sicher ist).
    -   `~` steht für ungefähre oder in etwa zutreffende Angaben (z. B. `1960~` bedeutet „ungefähr im Jahr 1960“).
    -   `%` steht für unsicher und ungefähr

3.  **Datumsbereiche und Intervalle**\
    Man kann Zeiträume als Intervalle ausdrücken, indem man zwei Daten mit einem Schrägstrich `/` verbindet:

    -   `1900/1950` steht für die Zeitspanne von 1900 bis 1950.
    -   Unvollständige Intervalle wie `1900/..` oder `../1950` drücken offene Zeiträume aus ("seit 1900" oder "bis 1950").
    -   Diese Intervalle können ebenfalls Unsicherheits- oder Ungefähr-Zeichen enthalten, um vage Zeiträume darzustellen: `1900~/1950?`.

4.  **Listen und Sets von Daten**\
    Man kann mehrere mögliche oder relevante Daten in einer Liste angeben:

    -   Eine Liste wie `[1960, 1962, 1965]` bedeutet eine explizite Aufzählung von möglichen oder relevanten Daten.

5.  **Jahreszeiten und Quartale**\
    EDTF erlaubt die Angabe von Jahreszeiten oder Quartalen, die in manchen Zusammenhängen relevant sein können:

    -   `1960-33` stellt beispielsweise die Angabe "Erstes Quartal des Jahres 1960" dar.
    -   Die Jahreszeiten Frühling, Sommer, Herbst und Winter sind mit den Codes `21`, `22`, `23` und `24` definiert, so kann beispielsweise "Frühling 1960" mit `1960-21` abgebildet werden.
    -   Die genauen Entsprechungen von Zeiten und Codes ist in der Spezifikation des EDTF-Standards festgelegt, um diese einheitlich anzugeben.

6.  **Jahrhunderte, Jahrzehnte und unvollständige Angaben**\
    Statt eines konkreten Jahres kann man ganze Jahrzehnte oder Jahrhunderte angeben:

    -   `19xx` für ein unbekanntes Jahr im 20. Jahrhundert.
    -   `19xx?` für ein ungefähres oder unsicheres Jahr im 20. Jahrhundert.
    -   `19uu` kann ähnlich verwendet werden, um Unsicherheit auf einer bestimmten Stellenebene auszudrücken.

7.  **Angaben von Jahren kleiner als -9999 und grösser 9999**

    -   `Y-30000` für 30'000 Jahre vor unserer Zeitrechnung.

EDTF bietet weit mehr Möglichkeiten als die Verwendung eines einfachen Kalenderdatums. Es erlaubt die Erfassung von Unsicherheiten, Unschärfen, komplexen Zeiträumen und offenen Enden, sowie die Angabe von Mengen, Intervallen oder wiederkehrenden Mustern. Das bedeutet im Kern: Wo man bislang nur ein genaues Datum hatte, lassen sich dank EDTF auch "ungefähr", "nicht genau bekannt", "innerhalb eines Jahrzehnts", "irgendwann zwischen X und Y" oder "eine von mehreren Möglichkeiten" in einem einheitlichen, standardisierten Format darstellen. Diese Flexibilität macht EDTF für historische, bibliothekarische, archivische oder wissenschaftliche Projekte besonders nützlich.