---
title: Auf dem Weg zu einer diskriminierungssensiblen Metadatenpraxis
subtitle: Erfahrungen aus einem Handbuchprojekt zur ethischen Auszeichnung historischer Quellen und Forschungsdaten
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliations:
        - Universität Basel
        - Universität Bern
  - name: Noëlle Schnegg
    orcid: 0009-0008-5207-6652
    email: noelle.schnegg@unibas.ch
    affiliation: Universität Basel
date: 2025-12-04
doi: 10.5281/zenodo.17751267
categories: Vortrag
event: ZB Zürich, Metadaten in den 'Humanities'
lang: de
bibliography: references.bib
nocite: |
  @*
citation:
  type: standard
  title: 'Auf dem Weg zu einer diskriminierungssensiblen Metadatenpraxis: Erfahrungen aus einem Handbuchprojekt zur ethischen Auszeichnung historischer Quellen und Forschungsdaten'
  container-title: 'Workshop: Metadaten in den Humanities, Zentralbibliothek Zürich'
appendix-cite-as: display
other-links:
  - text: Veranstaltungswebseite
    icon: house
    href: 'https://www.zb.uzh.ch/de/events/workshop-metadaten-in-den-humanities'
  - text: Slides (Zenodo)
    icon: file-pdf
    href: 'https://doi.org/10.5281/zenodo.17751267'
---

## Vortrag

Der Vortrag von Moritz Mähr und Noëlle Schnegg hat im Rahmen des [Workshops 'Metadaten in den Humanities'](https://www.zb.uzh.ch/de/events/workshop-metadaten-in-den-humanities) in der Zentralbibliothek Zürich stattgefunden.

::: {.callout-tip title="Präsentation anzeigen" icon="false" collapse="true"}

<iframe src="/assets/files/20251204-Maehr_Schnegg-Auf_dem_Weg_zu_einer_diskriminierungssensiblen_Metadatenpraxis.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="Auf dem Weg zu einer diskriminierungssensiblen Metadatenpraxis">

This browser does not support PDFs. Please <a href="/assets/files/20251204-Maehr_Schnegg-Auf_dem_Weg_zu_einer_diskriminierungssensiblen_Metadatenpraxis.pdf">download the PDF</a> to view it.

</iframe>
:::

## Abstract

Die Präsentation stellt konzeptionelle und praktische Überlegungen zur Entwicklung einer diskriminierungssensiblen Metadatenpraxis vor. Ausgehend von einem Handbuchprojekt im Rahmen des Forschungsprojekts Stadt.Geschichte.Basel diskutieren die Referent\*innen

- Herausforderungen bei der Publikation sensibler historischer Quellen im Netz,
- fehlende Standards und notwendige Best-Practices (2023),
- die theoretische Rahmung (Content Notes, Positionalität),
- konkrete Arbeitsprozesse der Quellenauswahl, Annotation, Kontextualisierung und Bereitstellung,
- den Überarbeitungszyklus des Handbuchs (Version 2.0) mit Fokus auf kuratorische Workflows und kritische Datenpraktiken.