---
title: Geodaten
author:
  - name: Nico Görlich
    orcid: 0000-0003-3860-1488
    affiliation: Universität Basel
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
date-modified: last-modified
lang: de
category: Other
---

## Geodaten

**Geodaten** sind digitale Informationen mit Raumbezug, die Objekte oder Ereignisse auf der Erdoberfläche beschreiben und deren genaue Position festlegen. Sie bestehen aus geometrischen Daten, wie Koordinaten, und den dazugehörigen Sachdaten, die Eigenschaften dieser Objekte beschreiben. Geodaten sind essenziell für die Erstellung von Karten und die Durchführung räumlicher Analysen in Geoinformationssystemen (GIS).

In den Bänden der **Stadt.Geschichte.Basel** spielen Geodaten eine zentrale Rolle. Sie ermöglichen es, historische Ereignisse, Entwicklungen und Strukturen der Stadt Basel präzise zu lokalisieren und räumlich darzustellen. Durch die Integration von Geodaten können beispielsweise alte Stadtpläne mit heutigen Karten überlagert werden, um Veränderungen im Stadtbild sichtbar zu machen. Zudem unterstützen Geodaten die Analyse von sozialen, wirtschaftlichen und infrastrukturellen Aspekten der Stadtgeschichte, indem sie räumliche Muster und Zusammenhänge aufzeigen. 

Die Veröffentlichung der Geodaten erfolgt bis Ende 2025. Die Daten werden in geeigneten Repositorien bereitgestellt und mit Metadaten versehen, um ihre Auffindbarkeit und Nachnutzung zu erleichtern. Die Geodaten von Stadt.Geschichte.Basel sind FAIR (Findable, Accessible, Interoperable, Reusable) und Open Access, um einen offenen Zugang zu den historischen Informationen zu gewährleisten.