---
title: Forschungsdatenplattform
subtitle: forschung.stadtgeschichtebasel.ch
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel
  - name: Nico Görlich
    orcid: 0000-0003-3860-1488
    affiliation: Universität Basel
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
date-modified: last-modified
lang: de
other-links:
  - text: Website
    icon: house
    href: 'https://forschung.stadtgeschichtebasel.ch/'
code-links:
  - href: 'https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/'
    text: GitHub Repository
    icon: github
---

## Plattform

Die [Forschungsdatenplattform von Stadt.Geschichte.Basel](https://forschung.stadtgeschichtebasel.ch/) ist eine öffentlich zugängliche digitale Ressource, die darauf abzielt, nachnutzbare Quellen und Daten zur Geschichte der Stadt Basel bereitzustellen. Sie ermöglicht es Forschenden, Studierenden und der interessierten Öffentlichkeit, auf eine Vielzahl von historischen Materialien zuzugreifen, darunter narrative Quellen, historische Texte, Bilder, Karten und audiovisuelle Medien. Diese Vielfalt fördert eine tiefere Auseinandersetzung mit den historischen Themen und unterstützt interdisziplinäre Forschung. Die Plattform befindet sich derzeit in der Testphase und wird kontinuierlich erweitert, mit einem geplanten Abschluss des Projekts Ende 2025. Die Datenaufbereitung erfolgt gemäss dem ["Handbuch zur Erstellung diskriminierungsfreier Metadaten für historische Quellen und Forschungsdaten"](/products/publications/handbuch/index.qmd), um eine inklusive und respektvolle Darstellung sicherzustellen.

Das zugehörige GitHub-Repository (https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/) enthält den Quellcode der Plattform und bietet Einblicke in die technische Umsetzung. Es basiert auf dem "CollectionBuilder-CSV"-Framework und ist unter der MIT-Lizenz veröffentlicht, was die offene Weiterentwicklung und Anpassung durch die Community ermöglicht. Interessierte Entwickler\*innen und Forschende können hier den Code einsehen, Beiträge leisten oder die Struktur für eigene Projekte adaptieren.

Insgesamt dient die Forschungsdatenplattform als wertvolles Werkzeug, um die reichhaltige Geschichte Basels zugänglich zu machen und den offenen Austausch von Wissen zu fördern.

## Datenmodell

Metadaten für die auf der Forschungsdatenplattform vorgestellten Elemente werden gemäss einem Datenmodell bereitgestellt, das vom Team für Forschungdatenmanagement der Stadt.Geschichte.Basel entwickelt wurde, um den Anforderungen der vielfältigen im Projekt verwendeten Quellen gerecht zu werden. Das Datenmodell (und der anschliessende Annotationsprozess) folgen dem Handbuch zur Erstellung diskriminerungsfreier Metadaten für historische Quellen und Forschungsdaten, das ebenfalls von Stadt.Geschichte.Basel entwickelt wurde.

Die folgende Grafik veranschaulicht das Datenmodell mit Metadatenfeldern für ein Beispiel-Metadatenobjekt `sgb01313`, das ein untergeordnetes Medienobjekt `m01313` hat. Wenn ein Metadatenobjekt mehr als ein untergeordnetes Medienobjekt hat, werden die id-Nummern der untergeordneten Objekte fortlaufend nummeriert: `m01313_1`, `m01313_2` usw.

```{mermaid}
classDiagram
direction LR
    class metadata {
        id (sgb01313)
        title
        [subject;subject]
        description
        temporal
        [isPartOf;isPartOf] (Data DOIs)
    }
    class media {
        id (m01313)
        title
        [subject;subject] (keywords from GenderOpen Index)
        description
        [creator] (incl. link to Wikidata)
        [publisher] (incl. link to Wikidata)
        date
        temporal
        type
        format
        extent
        [source] (Source and catalogue link)
        language (ISO 639-2 code)
        [relation] (internal links to other items, link to GitHub, further information)
        rights
        license
    }
    metadata "n" --> "m" media
```