---
title: Digital History Switzerland 2024
subtitle: 'Historical Research, Digital Literacy and Algorithmic Criticism'
categories:
- Veranstaltung
- Publikation
author:
  - name: Jérôme Baudry
    orcid: 0000-0002-9949-0681
    affiliation: EPFL
  - name: Lucas Burkart
    orcid: 0000-0002-9011-5113
    affiliation: Universität Basel
  - name: Béatrice Joyeux-Prunel
    orcid: 0000-0003-1046-7002
    affiliation: Université de Genève
  - name: Eliane Kurmann
    orcid: 0000-0002-9037-7260
    affiliation: infoclio.ch
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel, Universität Bern
  - name: Enrico Natale
    orcid: 0000-0002-0967-5931
    affiliation: infoclio.ch, Verein Geschichte und Informatik
  - name: Christiane Sibille
    orcid: 0000-0003-3689-2154
    affiliation: ETH Bibliothek, Verein Geschichte und Informatik
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
date: 2024-09-12
lang: de
citation:
  type: standard
other-links:
  - text: Veranstaltungswebseite
    icon: house
    href: 'https://digihistch24.github.io'
  - text: Zenodo Community
    icon: collection
    href: 'https://zenodo.org/communities/digihistch24'
code-links:
  - text: GitHub Repository
    icon: github
    href: 'https://github.com/digihistch24/digihistch24.github.io/'
---

## Konferenz

Die Webseite [digihistch24.github.io](https://digihistch24.github.io/) dient als zentrale Informationsplattform für die Konferenz "Digital History Switzerland 2024" mit dem Titel "Historical Research, Digital Literacy and Algorithmic Criticism". Diese fand am 12. und 13. September 2024 an der Universität Basel statt und bot Forschenden sowie Fachleuten die Möglichkeit, sich über die Integration digitaler Werkzeuge in die Geschichtswissenschaften auszutauschen. Die Webseite stellt unter anderem das Konferenzprogramm, den Call for Contributions und das Book of Abstracts zur Verfügung, welches eine umfassende Übersicht über die präsentierten Forschungsarbeiten bietet. citeturn0search0

Das zugehörige GitHub-Repository [digihistch24.github.io](https://github.com/digihistch24/digihistch24.github.io/) enthält den Quellcode der Webseite und ermöglicht es Interessierten, Einblicke in die technische Umsetzung zu gewinnen. Es basiert auf dem [open-research-data-template](/products/coding/ord-template/index.qmd) und fördert durch seine offene Struktur die Zusammenarbeit innerhalb der wissenschaftlichen Community.

Das Team von **Stadt.Geschichte.Basel** hat aktiv an der Organisation und Umsetzung der Konferenz mitgewirkt und somit einen bedeutenden Beitrag zur Förderung der digitalen Geschichtsforschung in der Schweiz geleistet.
