---
title: Digitale Sammlungen mit FAIR-Daten und Open Source Software erstellen
subtitle: Eine Einführung in CollectionBuilder
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel, Universität Bern
date: 2024-12-03
categories: Vortrag
event: Universität Bern, Coffee Lectures
lang: de
doi: 10.5281/zenodo.14267948
citation:
  type: standard
  title: 'Digitale Sammlungen mit FAIR-Daten und Open Source Software erstellen: Eine Einführung in CollectionBuilder'
  container-title: 'Coffee Lectures, Universität Bern'
appendix-cite-as: display
other-links:
  - text: Veranstaltungswebseite
    icon: house
    href: 'https://www.wbkolleg.unibe.ch/ueber_uns/oeffentlichkeit/veranstaltungen/coffee_lectures_im_herbstsemester_2024/index_ger.html'
  - text: Slides (Zenodo)
    icon: filetype-pdf
    href: 'https://doi.org/10.5281/zenodo.14267948'
---

## Vortrag

Der Vortrag fand im Rahmen der [Coffee-Lectures-Veranstaltungsreihe](https://www.wbkolleg.unibe.ch/ueber_uns/oeffentlichkeit/veranstaltungen/coffee_lectures_im_herbstsemester_2024/index_ger.html) am Walter-Benjamin-Kolleg der Universität Bern statt, ist auf Zenodo archiviert und [als PDF-Datei abrufbar](https://doi.org/10.5281/zenodo.14267948).

::: {.callout-tip title="Präsentation anzeigen" icon="false" collapse="true"}
<iframe src="/assets/files/241203 Digitale Sammlungen mit CollectionBuilder selbst erstellen.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="Digitale Sammlungen mit FAIR-Daten und Open Source Software erstellen">

This browser does not support PDFs. Please download the PDF <a href="/assets/files/241203 Digitale Sammlungen mit CollectionBuilder selbst erstellen.pdf">download the PDF</a> to view it.

</iframe>
:::

## Abstract

Erfahren Sie, wie Sie mit dem CollectionBuilder, einer einfach zu bedienenden Open Source Software, zugängliche und gut organisierte digitale Sammlungen erstellen können. In dieser Coffee Lecture werden die FAIR-Prinzipien (Findable, Accessible, Interoperable, Reusable) erläutert und gezeigt, wie CollectionBuilder diese Prinzipien umsetzt, um den Aufbau, die Pflege und die Veröffentlichung digitaler Sammlungen zu erleichtern. Die Teilnehmenden erhalten praktische Einblicke und sehen Beispiele aus der Praxis, darunter die Fallstudie der Forschungsdatenplattform Stadt.Geschichte.Basel. Sie lernen, wie sie ohne tiefere technische Kenntnisse eigene digitale Sammlungen erstellen, anpassen und pflegen können. Die Veranstaltung richtet sich an Forschende, Bibliothekar\*innen sowie an alle, die die Zugänglichkeit und Wirkung ihrer Forschungsdaten verbessern möchten.