# Über uns

Wir sind ein interdisziplinäres <a href="https://stadtgeschichtebasel.ch/projekt" target="_blank">Forschungsprojekt</a>, das sich der umfassenden Erforschung und Dokumentation der langen Geschichte von Basel widmet. Unsere Initiative wurde in den 1980er Jahren geboren, erhielt jedoch erst im Jahr 2011 durch einen Verein und das Departement Geschichte der Universität Basel neuen Schwung. Schliesslich wurde unser Projekt 2016 durch den Grossen Rat des Kantons Basel-Stadt unterstützt und genehmigt.

Unser Team besteht aus mehr als fünfzig engagierten Forscher\*innen und Mitarbeiter\*innen aus verschiedenen Ländern, die sich mit Hingabe der Erforschung und Darstellung der Basler Geschichte widmen.

Unser Ziel ist es, einen bedeutenden Beitrag zur Erforschung und Dokumentation der Geschichte von Basel zu leisten und gleichzeitig die Vergangenheit auf zeitgemässe Weise zugänglich zu machen. Wir freuen uns über Ihr Interesse und laden Sie ein, unsere Webseite zu erkunden und mehr über die faszinierende Geschichte von Basel zu erfahren.

Die <a href="https://stiftungen.stiftungschweiz.ch/organisation/stiftung-stadt-geschichte-basel" target="_blank">Stiftung Stadt.Geschichte.Basel</a> ist durch den <a href="https://stadtgeschichtebasel.ch/verein" target="_blank">Verein Basler Geschichte</a> am 9.1.2017 gegründet worden. Sie überwacht die Durchführung des Projekts und stellt durch ein Herausgebergremium die inhaltliche Qualität der Forschung sicher. Die Koordination der Forschung und die damit verbundene konzeptionelle und redaktionelle Arbeit ist Aufgabe der Projektleitung.

## Mitglieder des Stiftungsrates

- **Andreas Burckhardt**, Dr., ehemaliger Verwaltungsratspräsident Bâloise Group
- **Christoph Lanz**, Jurist, ehemaliger Leiter Abteilung Recht und Sekretär des Verwaltungsrates MCH Group AG (vormals Schweizer Mustermesse)
- **Antonia Schmidlin**, Dr., Historikerin, Gymnasiallehrerin, Vorstandsmitglied Verein Basler Geschichte
- **Barbara Schneider**, Alt Regierungsrätin Basel-Stadt, Richterin
- **Marie-Louise Stamm**, Dr., ehem. Vorsitzende Appellationsgericht, Richterin
- **Regina Wecker**, Prof. em. Dr., Historikerin, Vorstand Verein Basler Geschichte, Stiftungsratspräsidentin
- **Benedikt Wyss**, Historiker, Kurator

## Geldgeber (ab CHF 1’000.-)

- Bank J. Safra Sarasin AG
- Basel Tourismus
- Bell AG
- Christoph Merian Stiftung
- Dr. H. A. Vögelin-Bienz-Stiftung
- E. E. Zunft zu Hausgenossen
- Ernst Göhner Stiftung
- Felix Labhardt
- Historisch-Antiquarische Gesellschaft zu Basel
- Ing. A. Aegerter + Dr. O. Bosshardt AG
- Iseli Optik AG
- K. Schweizer AG
- Manor AG
- Max Geldner-Stiftung
- Moritz Straus-Stiftung
- Novartis
- PAX, Schweizerische Lebensversicherungs-Gesellschaft AG
- Raiffeisen Schweiz AG
- Rapp Management AG
- Schachenmann + Co. AG
- Swisslos-Fonds Basel-Landschaft
- Swisslos-Fonds Basel-Stadt
- Sulger-Stiftung
- UBS Kulturstiftung
- Verein Basler Geschichte
- Vischer Architekten AG
- Völlmy AG
- …und weitere Spender\*innen, die ungenannt bleiben möchten.

## Social Media

Wir sind unter <a href="https://www.instagram.com/sta.ge.ba/" target="_blank">sta.ge.ba</a> auf Instagram und unter <a href="https://twitter.com/basel_stadt" target="_blank">basel_stadt</a> auf X zu finden. Wir folgen dabei strikten <a href="https://stadtgeschichtebasel.ch/richtlinien-fuer-den-blog-und-soziale-medien" target="_blank">Richtlinien für den Blog und soziale Medien</a>.

## Medien und Pressemappe

- <a href="https://stadtgeschichtebasel.ch/pressemappe" target="_blank">Pressemappe</a>

Medienanfragen richten Sie bitte direkt an den <a href="https://www.merianverlag.ch/presse.html" target="_blank">Christoph Merian Verlag</a>.

## Lehrmittel

- <a href="https://stadtgeschichtebasel.ch/vermittlungsangebot-verschachtelte-geschichten-immigrationsschicksale-in-der-schweiz-in-den-letzten-hundert-jahren" target="_blank">«Verschachtelte Geschichten. Immigrationsschicksale in der Schweiz in den letzten hundert Jahren»</a> bietet Unterrichtsmaterial über 12 Immigrationsschicksale der letzten hundert Jahre.

Weitere Lehrmittel von Kooperationspartner\*innen und Dritten finden sich auf dem Basler Bildungsserver unter <a href="https://www.edubs.ch/" target="_blank">www.edubs.ch</a>.

# Impressum

Stiftung Stadt.Geschichte.Basel, Hirschgässlein 21, 4051 Basel. [info@stadtgeschichtebasel.ch](mailto:info@stadtgeschichtebasel.ch)

Redaktion: Moritz Mähr, Noëlle Schnegg und Cristina Wildisen-Münch

## Datenschutz

Zur <a href="https://stadtgeschichtebasel.ch/datenschutzerklaerung" target="_blank">Datenschutzerklärung</a>.

## Barrierefreiheit

Zur <a href="https://stadtgeschichtebasel.ch/barrierefreiheitserklaerung" target="_blank">Barrierefreiheitserklärung</a>.
