---
title: "Forschungsdatenmanagement und Public History"
lang: de
listing:
  - id: presentations-listing
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "Vortrag"
  - id: posters-listing
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "Poster"
  - id: workshops-listing
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "Workshop"
  - id: panels-listing
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "{Panel,Roundtable}*"
  - id: coding-listing
    type: grid
    contents: coding/*/index.qmd
    sort: "title"
    fields: [title, subtitle]
    grid-columns: 2
  - id: digital-history-listing
    type: grid
    categories: false
    contents: digital-history/*/index.qmd
    fields: [title]
  - id: interna-listing
    type: grid
    grid-columns: 2
    categories: true
    contents: interna/*/index.qmd
    fields: [title]
  - id: publications-listing
    type: grid
    grid-columns: 2
    categories: false
    contents: publications/*/index.qmd
    fields: [title, subtitle]
    include:
      categories: "Publikation"
  - id: datastories-listing
    type: grid
    grid-columns: 2
    categories: false
    contents: publications/*/index.qmd
    fields: [title, subtitle]
    include:
      categories: "Data Story"
  - id: research-data-listing
    type: grid
    contents: [research-data/*/index.qmd]
    fields: [title]
    grid-columns: 2
date-modified: last-modified
---

## Publikationen

::: {#publications-listing}
:::

### Data Stories

::: {#datastories-listing}
:::

## Coding

::: {#coding-listing}
:::

## Forschungsdaten

::: {#research-data-listing}
:::

## Vorträge, Poster und Workshops {#conferences}

Wissenschaftliche Veröffentlichungen, die im Zusammenhang mit dem Forschungsprojekt stehen, sind [auf Zenodo archiviert](https://zenodo.org/communities/stadt-geschichte-basel). Die im Rahmen von Konferenzen und Workshops publizierten Beiträge des Teams für Forschungsdatenmanagement und Public History befassen sich mit der Entwicklung der digitalen Angebote von Stadt.Geschichte.Basel und übergreifend mit (digitalem) Forschungsdatenmanagement und Public History in den Geschichtswissenschaften. Erfasst sind [Vorträge](#vorträge), die Organisation von bzw. Teilnahme an [Panels/Roundtables](#panels-und-roundtables), veranstaltete [Workshops](#workshops) sowie wissenschaftliche [Posterpräsentationen](#poster).

### Vorträge {#vorträge}

::: {#presentations-listing}
:::

### Panels und Roundtables {#panels-und-roundtables}

::: {#panels-listing}
:::

### Workshops {#workshops}

::: {#workshops-listing}
:::

### Poster {#poster}

::: {#posters-listing}
:::

## Community Building

::: {#digital-history-listing}
:::

## Interna

::: {#interna-listing}
:::