---
title: One Template to Rule Them All
subtitle: Interactive Research Data Documentation with Quarto
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliations:
        - University of Basel
        - University of Bern
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: University of Basel
date: 2025-10-22
categories: Publikation
lang: en
doi: 10.63744/X90VnKkYV5Hb
other-links:
  - text: Paper (HTML)
    icon: filetype-html
    href: 'https://doi.org/10.63744/X90VnKkYV5Hb'
  - text: Paper (PDF)
    icon: filetype-pdf
    href: '/assets/files/251022-Maehr_Twente-Template.pdf'
  - text: Digital Humanities Tech Symposium (DH2025) Presentation
    href: '/products/talks-posters/dhtech-ordtemplate/'
    icon: easel
code-links:
  - href: 'https://github.com/maehr/open-research-data-template'
    text: 'Template Repository'
    icon: github
  - href: 'https://github.com/achorg/anthology-ch/'
    text: anthology-ch Source Repository
    icon: github
---

The paper *One Template to Rule Them All: Interactive Research Data Documentation with Quarto* is part of the [proceedings of the Digital Humanities Tech Symposium](https://anthology.ach.org/volumes/vol0002/) at DH2025 in Lisbon ([Slides](/products/talks-posters/dhtech-ordtemplate/index.qmd)).

::: {.callout-tip title="Show Paper" icon="false" collapse="true"}
<iframe src="/assets/files/251022-Maehr_Twente-Template.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="One Template to Rule Them All: Interactive Research Data Documentation with Quarto">

This browser does not support PDFs. Please download the PDF <a href="/assets/files/251022-Maehr_Twente-Template.pdf">download the PDF</a> to view it.

</iframe>
:::

## Abstract

This paper introduces the [Open Research Data Template](/products/coding/ord-template/index.qmd), a modular, Quarto-based framework developed to enhance the documentation, publication, and reuse of research data in the Digital Humanities.

Originating from the Stadt.Geschichte.Basel project, the template addresses common challenges in research data management (RDM), such as poor documentation of data preprocessing and reuse pathways, by integrating narrative, metadata, and executable code into interactive, version-controlled websites. Built on [The Turing Way](https://book.the-turing-way.org/) guidelines and leveraging GitHub for collaboration and Zenodo for archival DOIs, the template enables automated deployment, consistent repository structure, and living, reproducible documentation.

Through diverse use cases, including project documentation, reproducible workflows, conference and teaching platforms, and living handbooks, the paper demonstrates the template’s flexibility and scalability. The authors argue that making robust, interactive documentation a default practice lowers technical barriers, improves sustainability, and fosters genuinely open and reusable research outputs. The widespread adoption of the template illustrates its value as a practical model for elevating open data standards and supporting the evolving needs of the Digital Humanities community.