---
title: Accessible Public History
subtitle: 'Digitale Sammlungen mit CollectionBuilder selbst erstellen'
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel
  - name: Nico Görlich
    orcid: 0000-0003-3860-1488
    affiliation: Universität Basel
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
  - name: Cristina Wildisen-Münch
    orcid: 0000-0003-3885-248X
    affiliation: Universität Basel
date: 2024-10-15
categories: Workshop
event: Praxislabor AG Digitale Geschichtswissenschaft
lang: de
doi: 10.58079/11sc7
citation:
  type: standard
  container-title: 'Praxislabor 2024 der AG Digitale Geschichtswissenschaft des Verbands der Historiker und Historikerinnen Deutschlands e.V.'
appendix-cite-as: display
other-links:
  - text: Veranstaltungswebseite
    icon: house
    href: 'https://doi.org/10.58079/11sc7'
---

## Workshop

Der Online-Workshop fand im Rahmen der Veranstaltungsreihe [Praxislabor 2024](https://doi.org/10.58079/w9uv) der AG Digitale Geschichtswissenschaft des Verbandes der Historiker und Historikerinnen Deutschlands statt.

## Abstract

In diesem Online-Workshop lernen die Teilnehmer:innen CollectionBuilder kennen. CollectionBuilder ist eine benutzerfreundliche Open Source-Software zur einfachen Erstellung und Verwaltung von digitalen Sammlungen und Ausstellungen. Mit seinem minimalistischen Ansatz demokratisiert CollectionBuilder Public History. Es gibt Forscher:innen, akademischen und GLAM-Institutionen die Möglichkeit, eine übersichtliche Website zur Vermittlung digitaler Ressourcen zu erstellen und zu pflegen, ohne über umfangreiche technische Kenntnisse oder eine entsprechende Infrastruktur verfügen zu müssen.

Das Team von Stadt.Geschichte.Basel nutzt das Tool, um Forschungsdaten des historischen Forschungsprojekts öffentlich zugänglich zu machen. Die Teilnehmenden des Workshops können daher einen umfassenden Einblick in die direkte Anwendung des Tools anhand einer aktuellen Fallstudie erwarten.

Die Teilnehmer:innen werden lernen:

* CollectionBuilder einzurichten und seine Funktionen zu nutzen.
* Digitale Exponate mit ihren eigenen Forschungsdaten zu erstellen und zu verwalten.
* Das Potenzial von Open-Source-Tools in der Public History und den Digital Humanities zu verstehen.

Für die Teilnahme sind erste Erfahrungen mit GitHub bzw. GitHub Pages, ggfs. auch Jekyll, hilfreich. Die Teilnehmer:innen brauchen einen Laptop und eine stabile Internetverbindung. Alle anderen Materialien, einschliesslich umfassender Dokumentation und Zugang zu einer CollectionBuilder-Instanz, werden zur Verfügung gestellt.

### Adressat:innen

Dieser Workshop ist ideal für Historiker:innen, Bibliothekar:innen, Archivar:innen, Studierende der Geisteswissenschaften und Citizen Scientists, die daran interessiert sind, historische Daten online aufzubereiten und zu präsentieren.

Registrierung: via [info@stadtgeschichtebasel.ch](mailto:info@stadtgeschichtebasel.ch)

Kontakt: [Moritz Twente](mailto:moritz.twente@unibas.ch)

Weitere Informationen: [forschung.stadtgeschichtebasel.ch](https://forschung.stadtgeschichtebasel.ch/workshops)